name: Linting Pipeline

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install

      - name: Ensure Correct Permissions for HTMLHint
        run: chmod +x ./node_modules/.bin/htmlhint

      - name: Check for HTML Files
        run: '[ "$(find src -name "*.html" | wc -l)" -gt 0 ] && npx htmlhint src/**/*.html || echo "No HTML files found."'

      - name: Check for CSS Files
        run: '[ "$(find styles -name "*.css" | wc -l)" -gt 0 ] && npx stylelint styles/**/*.css || echo "No CSS files found."'
